### ISSUE TITLE
go: finding github.com/sclevine/agouti v3.0.0+incompatible error on Dotnet core deployment

### ISSUE THREAD

**Issue by tpardhu561** [cloudfoundry/dotnet-core-buildpack#200]
CF version 2.2.8-build.12
CF CLI version 6.40.1+85d04488a.2018-10-31

Buildpack version 2.1.5

I'm try to push my app.

My app is published one. I just refer to the zip package of publish folder.
Expected a successful deployment but I'm seeing below errors from my Jenkins log.

Although I see similar logs for other apps, I was still able to deploy them but not for this app.
Below is the log from Jenkins.

Creating app with these attributes...
+ name:         ServiceDev
  path:         ServiceDev.zip
  buildpacks:
+   https://github.com/cloudfoundry/dotnet-core-buildpack.git
+ instances:    1
+ memory:       1G
  env:
+   APPLICATION_NAME
+   ENVIRONMENT_NAME
  routes:
+   ServiceDev .apps.nprd-pcf.xyz.net

Creating app ServiceDev ...
Mapping routes...
Comparing local files to remote cache...
Packaging files to upload...
Uploading files...

 0 B / 303.59 KiB    0.00%
 288.00 KiB / 303.59 KiB   94.87%
 303.59 KiB / 303.59 KiB  100.00%
 303.59 KiB / 303.59 KiB  100.00%
 303.59 KiB / 303.59 KiB  100.00%
 303.59 KiB / 303.59 KiB  100.00%
 303.59 KiB / 303.59 KiB  100.00%
 303.59 KiB / 303.59 KiB  100.00%
 303.59 KiB / 303.59 KiB  100.00% 1s

Waiting for API to complete processing files...

Staging app and tracing logs...
   Cell 029cf6b3-494d-405c-baf4-6ec9b38df8dc creating container for instance 99ed06d7-0a4a-42a6-84ca-5b6c75bad1e9
   Cell 029cf6b3-494d-405c-baf4-6ec9b38df8dc successfully created container for instance 99ed06d7-0a4a-42a6-84ca-5b6c75bad1e9
   Downloading app package...
   Downloaded app package (7.9M)
   -----> Download go 1.11.2
   -----> Running go build supply
   /tmp/buildpackdownloads/c405f3cc2cbad82abd8c07e23d682835 ~
   go: finding github.com/sclevine/agouti v3.0.0+incompatible
   go: finding github.com/go-ini/ini v1.39.1
   go: finding github.com/kr/text v0.1.0
   go: finding github.com/golang/mock v1.1.1
   go: finding github.com/cloudfoundry/libbuildpack v0.0.0-20181203192608-40fcf6231d2e
   go: finding golang.org/x/sys v0.0.0-20181128092732-4ed8d59d0b35
   go: finding golang.org/x/tools v0.0.0-20181201035826-d0ca3933b724
   go: finding gopkg.in/yaml.v2 v2.2.2
   go: finding cloud.google.com/go v0.33.1
   go: finding go4.org v0.0.0-20181109185143-00e24f1b2599
   go: finding github.com/elazarl/goproxy v0.0.0-20181111060418-2ce16c963a8a
   go: finding github.com/Masterminds/semver v1.4.2
   go: finding golang.org/x/net v0.0.0-20181201002055-351d144fa1fc
   go: finding github.com/rogpeppe/go-charset v0.0.0-20180617210344-2471d30d28b4
   go: finding github.com/jtolds/gls v4.2.1+incompatible
   go: finding github.com/smartystreets/assertions v0.0.0-20180927180507-b2de0cb4f26d
   go: finding golang.org/x/crypto v0.0.0-20181203042331-505ab145d0a9
   go: finding gopkg.in/jarcoal/httpmock.v1 v1.0.0-20181117152235-275e9df93516
   go: finding golang.org/x/build v0.0.0-20181121152522-2b0e3d65700e
   go: finding github.com/blang/semver v3.5.1+incompatible
   go: finding golang.org/x/text v0.3.1-0.20180807135948-17ff2d5776d2
   go: finding github.com/smartystreets/goconvey v0.0.0-20181108003508-044398e4856c
   go: finding gopkg.in/yaml.v2 v2.2.1
   go: finding github.com/tidwall/match v1.0.0
   go: finding code.cloudfoundry.org/bytefmt v0.0.0-20180906201452-2aa6f33b730c
   go: finding gopkg.in/jarcoal/httpmock.v1 v1.0.0-20181025172632-c463961d8bfe
   go: finding github.com/inconshreveable/go-vhost v0.0.0-20160627193104-06d84117953b
   go: finding github.com/kr/pty v1.1.1
   go: finding gopkg.in/ini.v1 v1.39.1
   go: finding gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405
   go: finding github.com/BurntSushi/toml v0.3.1
   go: finding github.com/tidwall/gjson v1.1.3
   go: finding github.com/onsi/gomega v1.4.3
   go: finding github.com/google/subcommands v0.0.0-20181012225330-46f0354f6315
   go: finding github.com/onsi/ginkgo v1.7.0
   go: finding github.com/davecgh/go-spew v1.1.1
   go: finding github.com/coreos/go-systemd v0.0.0-20181012123002-c6f51f82210d
   go: finding github.com/pmezard/go-difflib v1.0.0
   go: finding github.com/microcosm-cc/bluemonday v1.0.1
   go: finding github.com/google/go-github v17.0.0+incompatible
   go: finding github.com/google/go-querystring v1.0.0
   go: finding github.com/gliderlabs/ssh v0.1.1
   go: finding github.com/sourcegraph/annotate v0.0.0-20160123013949-f4cad6c6324d
   go: finding github.com/googleapis/gax-go v2.0.0+incompatible
   go: finding google.golang.org/appengine v1.2.0
   go: finding github.com/kr/pty v1.1.3
   go: finding golang.org/x/net v0.0.0-20180906233101-161cd47e91fd
   go: finding github.com/fsnotify/fsnotify v1.4.7
   go: finding github.com/shurcooL/events v0.0.0-20181021180414-410e4ca65f48
   go: finding golang.org/x/oauth2 v0.0.0-20181017192945-9dcd33a902f4
   go: finding github.com/shurcooL/sanitized_anchor_name v0.0.0-20170918181015-86672fcb3f95
   go: finding github.com/shurcooL/httpfs v0.0.0-20171119174359-809beceb2371
   go: sourcegraph.com/sourcegraph/go-diff@v0.5.0: unrecognized import path "sourcegraph.com/sourcegraph/go-diff" (parse https://sourcegraph.com/sourcegraph/go-diff?go-get=1: no go-import meta tags (meta tag 127.0.0.1:3080/sourcegraph/go-diff did not match import path sourcegraph.com/sourcegraph/go-diff))
   go: finding github.com/shurcooL/gofontwoff v0.0.0-20180329035133-29b52fc0a18d
   go: finding dmitri.shuralyov.com/app/changes v0.0.0-20180602232624-0a106ad413e3
   go: finding github.com/neelance/sourcemap v0.0.0-20151028013722-8c68805598ab
   go: finding google.golang.org/api v0.0.0-20181030000543-1d582fd0359e
   go: finding gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
   go: finding github.com/shurcooL/home v0.0.0-20181020052607-80b7ffcb30f9
   go: finding github.com/kr/pretty v0.1.0
   go: finding github.com/shurcooL/notifications v0.0.0-20181007000457-627ab5aea122
   go: finding dmitri.shuralyov.com/state v0.0.0-20180228185332-28bcc343414c
   go: finding github.com/gregjones/httpcache v0.0.0-20180305231024-9cad4c3443a7
   go: finding github.com/shurcooL/issuesapp v0.0.0-20180602232740-048589ce2241
   go: finding github.com/dustin/go-humanize v1.0.0
   go: finding github.com/shurcooL/github_flavored_markdown v0.0.0-20181002035957-2122de532470
   go: finding github.com/neelance/astrewrite v0.0.0-20160511093645-99348263ae86
   go: finding github.com/hpcloud/tail v1.0.0
   go: finding dmitri.shuralyov.com/service/change v0.0.0-20181023043359-a85b471d5412
   go: finding github.com/shurcooL/highlight_go v0.0.0-20181028180052-98c3abbbae20
   go: finding github.com/shurcooL/issues v0.0.0-20181008053335-6292fdc1e191
   go: finding golang.org/x/sync v0.0.0-20180314180146-1d60e4601c6f
   go: finding golang.org/x/tools v0.0.0-20181030000716-a0a13e073c7b
   go: finding dmitri.shuralyov.com/html/belt v0.0.0-20180602232347-f7d459c86be0
   go: finding go.opencensus.io v0.18.0
   go: finding github.com/bradfitz/go-smtpd v0.0.0-20170404230938-deb6d6237625
   go: finding golang.org/x/time v0.0.0-20180412165947-fbb02b2291d2
   go: finding gopkg.in/inf.v0 v0.9.1
   go: finding github.com/shurcooL/reactions v0.0.0-20181006231557-f2e0b4ca5b82
   go: finding github.com/gopherjs/gopherjs v0.0.0-20181017120253-0766667cb4d1
   go: finding golang.org/x/crypto v0.0.0-20181030102418-4d3f4d9ffa16
   go: finding github.com/google/go-cmp v0.2.0
   go: finding github.com/tarm/serial v0.0.0-20180830185346-98f6abe2eb07
   go: finding github.com/google/martian v2.1.0+incompatible
   go: finding golang.org/x/perf v0.0.0-20180704124530-6e6d33e29852
   go: finding github.com/onsi/ginkgo v1.6.0
   go: finding cloud.google.com/go v0.31.0
   go: finding github.com/flynn/go-shlex v0.0.0-20150515145356-3f9db97f8568
   go: finding github.com/golang/protobuf v1.2.0
   go: finding google.golang.org/genproto v0.0.0-20181029155118-b69ba1387ce2
   go: finding golang.org/x/sys v0.0.0-20180909124046-d0be0721c37e
   go: finding golang.org/x/net v0.0.0-20181029044818-c44066c5c816
   go: finding github.com/shurcooL/component v0.0.0-20170202220835-f88ec8f54cc4
   go: finding gopkg.in/fsnotify.v1 v1.4.7
   go: finding github.com/shurcooL/httpgzip v0.0.0-20180522190206-b1c53ac65af9
   go: finding github.com/sourcegraph/syntaxhighlight v0.0.0-20170531221838-bd320f5d308e
   go: finding github.com/jellevandenhooff/dkim v0.0.0-20150330215556-f50fe3d243e1
   go: finding golang.org/x/sys v0.0.0-20181029174526-d69651ed3497
   go: finding github.com/shurcooL/users v0.0.0-20180125191416-49c67e49c537
   go: finding github.com/stretchr/testify v1.2.2
   go: finding github.com/shurcooL/htmlg v0.0.0-20170918183704-d01228ac9e50
   go: finding go4.org v0.0.0-20180809161055-417644f6feb5
   go: finding github.com/shurcooL/webdavfs v0.0.0-20170829043945-18c3829fa133
   go: finding github.com/shurcooL/gopherjslib v0.0.0-20160914041154-feb6d3990c2c
   go: finding github.com/shurcooL/octicon v0.0.0-20181028054416-fa4f57f9efb2
   go: finding golang.org/x/text v0.3.0
   go: finding github.com/anmitsu/go-shlex v0.0.0-20161002113705-648efa622239
   go: finding github.com/sergi/go-diff v1.0.0
   go: finding github.com/shurcooL/highlight_diff v0.0.0-20170515013008-09bb4053de1b
   go: finding grpc.go4.org v0.0.0-20170609214715-11d0a25b4919
   go: finding google.golang.org/grpc v1.16.0
   go: finding github.com/shurcooL/httperror v0.0.0-20170206035902-86b7830d14cc
   go: error loading module requirements
   Failed to compile droplet: Failed to run all supply scripts: exit status 1
Error staging application: App staging failed in the buildpack compile phase
FAILED

Sometimes I see "TLS Handshake Timeout" error as well.

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by ahaleiii** [comment]
We are experiencing this issue as well. We had to change all our .NET Core buildpacks to be `https://github.com/cloudfoundry/dotnet-core-buildpack.git#v2.2.0`. It looks like the recent changes to how the buildpack handles `go` is causing issues, as well as 33% increase in cf push times. (We're at 2 minutes; if we take the latest, then it takes around 3 minutes.)

**Comment by sclevine** [comment]
Sorry for the trouble -- we'll investigate this soon. In the meantime, you can push with:
`-b https://github.com/cloudfoundry/dotnet-core-buildpack/releases/download/v2.2.1/dotnet-core-buildpack-cflinuxfs3-v2.2.1.zip`

This should be much faster, because it uses pre-compiled go code.

**Comment by dwillist** [comment]
Hi @tpardhu561 - we are unable to reproduce this issue with the v2.2.1 buildpack. Any chance you could provide us with a sample app?

**Comment by sclevine** [comment]
This seems to be network related. For now, let's re-introduce vendoring and build with `-mod=vendor`.

**Comment by tpardhu561** [comment]
I'm afraid that I'll not be able to share a sample app. We are not seeing this issue when using pre-compiled go code in the build pack as suggested by @sclevine

**Comment by dwillist** [comment]
Ok, closing as this seems to be resolved.

**Comment by tpardhu561** [comment]
Not sure on how this could be moved to closed. We are not seeing issues when we are hard coding the buildpack URL like -b https://github.com/cloudfoundry/dotnet-core-buildpack/releases/download/v2.2.1/dotnet-core-buildpack-cflinuxfs2-v2.2.1.zip and this is not a good practice. The above one is a temporary solution.

We don't want to change the URL every time when a newer version of .NET core is being used in our apps.  I want to use -b https://github.com/cloudfoundry/dotnet-core-buildpack.git and I would still see this issue when I use this.

**Comment by ahaleiii** [comment]
I agree with @tpardhu561 in that I would like to be using the latest version of the buildpack, not a workaround. If I were to bullet point some requirements, they would be:
- Ability to reference latest version of buildpack
- Ability to reference version with pre-compiled go code

Framed as user stories:
- As a consumer of the dotnet buildpack, I want the ability to have a single reference to the latest version of the buildpack. I do not want to have to update this reference when a newer version of the buildpack is released. I do not want to have to install a new buildpack into my PCF installation when a newer version of the buildpack is released.
- As a consumer of the dotnet buildpack, I want my `cf push` times to be as small as possible. I do not want to have to download or compile extra things; I want my app to get pushed out so that I can start using it.

I am envisioning a link that would look similar to: `https://.../dotnet-core-buildpack-cflinuxfs3-latest.zip`

**Comment by ahaleiii** [comment]
@sclevine Any updates on this? Is there somewhere I can go to see progress?

**Comment by sclevine** [comment]
This issue was fixed many releases ago. The buildpack dependencies are now vendored.

We have no immediate plans to move to buildpacks.cloudfoundry.org for distribution, given that Cloud Native Buildpacks will change the model significantly.

**Comment by ahaleiii** [comment]
@sclevine Thanks for the update, I will experiment with using the latest releases. Appreciate your response!

**Comment by cruiser1789** [comment]
I am still facing this issue:
 finding github.com/golang/lint v0.0.0-20181026193005-c67002cb31c3
go: finding golang.org/x/time v0.0.0-20180412165947-fbb02b2291d2
go: finding github.com/shurcooL/octicon v0.0.0-20181028054416-fa4f57f9efb2
go: finding golang.org/x/sync v0.0.0-20180314180146-1d60e4601c6f
go: finding github.com/shurcooL/htmlg v0.0.0-20170918183704-d01228ac9e50
go: error loading module requirements
make: *** [make] Error 1
